version: 2.1
jobs:
  deploy-heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
orbs:
  cypress: cypress-io/cypress@1
  heroku: circleci/heroku@1.2.6
workflows:
    build:
      jobs:
        - cypress/run:
            group: 'all tests' # name this group "all tests" on the dashboard
            start: 'npm start' # start server before running tests
        - kramdown:
            input: Kramdown
        - deploy-heroku:
            requires:
              - cypress/run
            filters:
              branches:
                only:
                - main  